language: node_js
node_js: 5

cache:
  directories:
    - node_modules/

before_install:
  - npm install -g aurelia-cli
  - pip install requests

script:
  - ci/build_app.sh

after_success:
  - commit_hash=`git rev-parse --short HEAD`
  - label="`date +%Y%m%d%H%M-$commit_hash`"
  - mv android.apk churchconnect_mobile-app_android-$label.apk
  - mv iphone.ipa churchconnect_mobile-app_ios-$label.ipa
  - mv phonegap_code.zip churchconnect_mobile-app_phonegap_src-$label.zip
  - ci/generate_manifest.py https://s3.amazonaws.com/$ARTIFACTS_BUCKET/mobile-app/unstable/churchconnect_mobile-app_ios-$label.ipa
  - mkdir churchconnect_mobile-app_ios-$label
  - mv manifest.plist churchconnect_mobile-app_ios-$label/manifest.plist

addons:
  artifacts:
    paths: $(ls *.apk *.zip *.ipa churchconnect_mobile-app_ios-$label | tr "\n" ":")
    target_paths: mobile-app/unstable/
    permissions: public-read
